development:
  adapter: postgresql
  encoding: unicode
  database: flashd_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: flashd_test
  pool: 5
  username:
  password:
