# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ede488d0f162609ad18f9198fae1114fb57e9f76c7975649ed5b1fa3246c46b6191e9985fe07d69f1e04eaf1c469581b18b0593b6335b12b1e28778d05d8286c

test:
  secret_key_base: 1d653a4a8bd612e0ab4b8cdd6f6e0f8f0cb257c4ca7d3535f8b19405b5cd3e3b4c88a2c4086dd870644cb6e3e17539b846e05de4fb700e1da5a79a43c481b923

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
